from enum import Enum
from typing import Optional, Dict, Any, List
from pydantic import BaseModel, ConfigDict, Field
from app.core.custom_types import UnitType

# 1. The Base Model
# Properties shared by all versions of the object
class LawUnitBase(BaseModel):
    id: str = Field(..., description="Canonical ID (e.g., 'art_102_alin_2')")
    content: str = Field(..., description="The actual legal text")
    unit_type: UnitType

    # Metainfo is a flexible dictionary for things like breadcrumbs or chapter titles
    meta_info: Dict[str, Any] = Field(default_factory=dict)

    model_config = ConfigDict(from_attributes=True)


# 2. Creation DTO (Input)
# Used by the Ingestion Pipeline to WRITE data (for postgres and other uses)
class LawUnitCreate(LawUnitBase):
    parent_id: Optional[str] = None

#3. Enrichement DTO
#Used for communication with the Qdrant database
class LawUnitEnriched(LawUnitCreate):
    """
    DTO carrying the AI-enriched data destined for Qdrant.
    """
    hypothetical_questions: List[str] = Field(
        default_factory=list,
        description="Distinct questions generated by the Ollama LLM"
    )
    content_vector: Optional[List[float]] = Field(
        default=None,
        description="Dense embedding of the raw legal content"
    )
    question_vectors: Optional[List[List[float]]] = Field(
        default=None,
        description="List of dense embeddings, mapping 1:1 to hypothetical_questions"
    )

# 4. Response DTO (Output)
# Used by the API to READ data (in the future will be sent to the spring application)
class LawUnitResponse(LawUnitBase):
    parent_id: Optional[str] = None
    model_config = ConfigDict(from_attributes=True)